[workspace]
members = ["projects/*"]
default-members = [
    "projects/ackerman",
    "projects/ackerman-qqbot",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
#panic = "abort"
