[normal]
"虚拟主播" = "virtual youtuber"
"黑长直" = "evil, black long hair, school, {school uniform}, {1girl}"
test1 = "1girl, light blonde hair, fluffy medium-short hair, bangs, 1_slim_red_ribbon on left hair, red eyes, {Round eyes}, rounded Eyelids, Brilliant smile, collared shirt, red and grey Military highschool dress, Fuller face, nishikigi_chisato, lycoris_recoil"
test2 = "1girl, masterpiece, hatsune miku, blow wind, cyan hair, two side up, cyan eyes, eardrop, dress, turning back, look at viewer, caustics, masterpiece, high resolution, wallpaper night soft ambient lighting lens flare beautiful composition HQ"
"简易花嫁" = "1girl, masterpiece, Daiwa Scarlet, umamusume, blow wind, brown hair, blush, smile,long hair, two side up, red eyes, eardrop, wedding dress, church, holding flower,white flower, wedding ring, look at viewer, caustics, masterpiece, high resolution,wallpaper night soft ambient lighting lens flare beautiful composition HQ"


[ss]
"简易涩涩" = "heart-shaped pupils, full-face blush, steam, sweat, lovestruck, tongue out, embarrassed, see-though, wet clothes, torn patyhose, cameltoe"
