name: Publish NAI
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
#          - os: ubuntu-latest
#            artifact_name: nai
#            asset_name: nai-linux-amd64
          - os: windows-latest
            artifact_name: nai.exe
            asset_name: nai.exe
#          - os: macos-latest
#            artifact_name: nai
#            asset_name: nai-mac-amd64

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cargo build --release
          ls target/release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}